---
title: "Examples"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{patentsview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Which patents have been cited by more than 500 US patents?

```{r}
library(patentsview)

search_pv(query = qry_funs$gt(patent_num_cited_by_us_patents = 500))
```

How many distinct inventors are represented by these highly-cited patents?

```{r}
# Setting subent_cnts = TRUE will give us the subentity counts. Since inventors 
# are subentities for the patents endpoint, this means we will get their counts.
search_pv(query = qry_funs$gt(patent_num_cited_by_us_patents = 500),
          fields = c("patent_number", "inventor_id"), subent_cnts = TRUE)
```

Where geographically have Microsoft inventors been coming from over the past 20 years?

```{r}
# Write the query
query <- with_qfuns(
  and(
    gte(patent_date = "2007-07-25"), # Dates are in yyyy-mm-dd format 
    contains(assignee_organization = "microsoft")
  )
)

# Create a field list
inv_fields <- get_fields(endpoint = "patents", groups = "inventors")
fields <- c(inv_fields, "patent_number")

# Pull the data
pv_out <- search_pv(query = query, fields = fields, all_pages = TRUE)

# Unnest the inventor list column
unnest_pv_data(data = pv_out$data, pk = "patent_number")
```

How many patents were published in each NBER subcategory during the years 1991, 2001, and 2011?

```{r}
search_pv(query = qry_funs$eq(year_id = c(1991, 2001, 2011)),
          endpoint = "nber_subcategories", all_pages = TRUE,
          fields = c("year_id", "nber_subcategory_id", "nber_subcategory_title",
                     "year_num_patents_for_nber_subcategory"))
```

Which assignees have an interest in beer?

```{r}
search_pv(query = qry_funs$text_phrase(patent_title = "beer"), 
          endpoint = "assignees")
```