---
title: "Assignees"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Assignees}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", warning = FALSE,
                      message = FALSE)
```

```{r}
library(patentsview)
library(dplyr)
library(highcharter)
library(DT)
library(knitr)

query <- with_qfuns(
  or(
    text_phrase(patent_abstract = "database"),
    text_phrase(patent_title = "database")
  )
)

query

fields <- c("patent_number", "assignee_organization",
            "patent_num_cited_by_us_patents", "app_date", "patent_date",
            "assignee_total_num_patents")

pv_out <- search_pv(query = query, fields = fields,
                    endpoint = "patents", all_pages = TRUE)

dl <- unnest_pv_data(data = pv_out$data, pk = "patent_number")
dl
```

```{r}
top_asgns <-
  dl$assignees %>%
    filter(!is.na(assignee_organization)) %>% # some patents are not assigned to an org
    mutate(ttl_pats = as.numeric(assignee_total_num_patents)) %>%
    group_by(assignee_organization, ttl_pats) %>% # group by ttl_pats so we can retain ttl_pats
    summarise(db_pats = n()) %>% 
    mutate(frac_db_pats = round(db_pats / ttl_pats, 3)) %>%
    ungroup() %>%
    select(c(1, 3, 2, 4)) %>%
    arrange(desc(db_pats)) 

datatable(
  data = top_asgns,
  rownames = FALSE,
  colnames = c("Assignee", "DB patents","Total patents", 
               "DB patents / total patents"),
  caption = htmltools::tags$caption(
    style = 'caption-side: top; text-align: left; font-style: italic;',
    "Table 1: Top assignees in 'databases'"
  ),
  options = list(pageLength = 10)
)
```

<br>

```{r}
top_asgns %>%
  select(-contains("pats")) %>%
  slice(1:5) %>%
  inner_join(dl$assignees) %>%
  inner_join(dl$applications) %>%
  mutate(app_yr = as.numeric(substr(app_date, 1, 4))) %>%
  group_by(assignee_organization, app_yr) %>%
  count() %>%
  hc_add_series_df(highchart(), data = ., "line", x = app_yr, y = n,
                   group = assignee_organization) %>%
  hc_plotOptions(series = list(marker = list(enabled = FALSE))) %>%
  hc_xAxis(title = list(text = "Application year")) %>%
  hc_yAxis(title = list(text = "DB patents")) %>%
  hc_title(text = "Top five assignees in 'databases'") %>%
  hc_subtitle(text = "Number of yearly patent applications over time")
```

```{r}
percent_rank2 <- function(x)
  (rank(x, ties.method = "average", na.last = "keep") - 1) / (sum(!is.na(x)) - 1)

asng_p_dat <-
  dl$patents %>%
    mutate(patent_yr = substr(patent_date, 1, 4)) %>%
    group_by(patent_yr) %>%
    mutate(perc_cite = percent_rank2(patent_num_cited_by_us_patents)) %>%
    inner_join(dl$assignees) %>%
    group_by(assignee_organization) %>%
    summarise(mean_perc = mean(perc_cite)) %>%
    inner_join(top_asgns) %>%
    arrange(desc(ttl_pats)) %>%
    filter(!is.na(assignee_organization)) %>%
    slice(1:20) %>%
    mutate(color = "#f1c40f") %>%
    as.data.frame()

kable(head(asng_p_dat), row.names = FALSE)
```

Adapted from http://jkunst.com/highcharter/showcase.html

```{r}
hchart(asng_p_dat, "scatter", hcaes(x = db_pats, y = mean_perc, size = frac_db_pats,
                                    group = assignee_organization, color = color)) %>%
  hc_xAxis(title = list(text = "DB patents"), type = "logarithmic",
           allowDecimals = FALSE) %>%
  hc_yAxis(title = list(text = "Mean cite perc.")) %>%
  hc_title(text = "Top assignees in 'databases'") %>%
  hc_add_theme(hc_theme_flatdark()) %>%
  hc_tooltip(useHTML = TRUE, pointFormat = tooltip_table(
    x = c("DB patents", "Mean cite percentile", "Fraction DB patents"),
    y = c("{point.db_pats:.0f}","{point.mean_perc:.2f}", "{point.frac_db_pats:.3f}")
  )) %>%
  hc_legend(enabled = FALSE)
```