---
title: "Citation relationships"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Assignees}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", warning = FALSE,
                      message = FALSE)
```

The following is a brief foray into patent citation networks (it is a __WIP__).

1. The first step is to download the relevant data fields from the PatentsView API:

```{r}
library(patentsview)
library(dplyr)
library(visNetwork)
library(magrittr)
library(stringr)

query <- qry_funs$begins(cpc_subgroup_id = "Y10S707/933")

fields <- c("cited_patent_number", "citedby_patent_number", "patent_number",
            "patent_title")

res <- search_pv(query = query, fields = fields, all_pages = TRUE)

res_lst <- unnest_pv_data(res$data, pk = "patent_number")
```

```{r}
edges <-
  res_lst$cited_patents %>%
    semi_join(x = ., y = ., by = c("cited_patent_number" = "patent_number")) %>%
    set_colnames(c("from", "to"))

pat_title <- function(title, number) {
  temp_title <- str_wrap(title)
  gsub("\\n", "<br>", temp_title) -> i
  paste0('<a href="https://patents.google.com/patent/US', number, '">', i, '</a>')
}

nodes <-
  res_lst$patents %>%
    mutate(id = patent_number, label = patent_number,
           title = pat_title(patent_title, patent_number))

visNetwork(nodes = nodes, edges = edges) %>%
  visEdges(arrows = list(to = list(enabled = TRUE, scaleFactor = 2))) %>%
  visOptions(highlightNearest = TRUE) %>%
  visIgraphLayout()
```

```{r}
res_lst2 <- lapply(
  res_lst, function(x) x[x$patent_number %in%
                           c("7797336", "9075849", "6499026"), ]
)

rel_pats <-
  res_lst2$cited_patents %>%
    rbind(setNames(res_lst2$citedby_patents, names(.))) %>%
    select(-patent_number) %>%
    rename(patent_number = cited_patent_number) %>%
    bind_rows(data.frame(patent_number = res_lst2$patents$patent_number)) %>%
    distinct() %>%
    filter(!is.na(patent_number))

rel_pats_res <- search_pv(query = list(patent_number = rel_pats$patent_number),
                          fields =  c("cited_patent_number", "patent_number",
                                      "patent_title"), all_pages = TRUE,
                          method = "POST")

rel_pats_lst <- unnest_pv_data(rel_pats_res$data, pk = "patent_number")
```

```{r}
edges <-
  rel_pats_lst$cited_patents %>%
    semi_join(x = ., y = ., by = c("cited_patent_number" = "patent_number")) %>%
    set_colnames(c("from", "to"))

nodes <-
  rel_pats_lst$patents %>%
    rename(id = patent_number) %>%
    mutate(color = ifelse(id %in% c("7797336", "9075849", "6499026"), "#CC6677",
                          "#DDCC77"), label = id,
           title = pat_title(patent_title, id))

visNetwork(nodes = nodes, edges = edges) %>%
  visEdges(arrows = list(to = list(enabled = TRUE, scaleFactor = 2)),
           color = list(color = "#4477AA")) %>%
  visOptions(highlightNearest = list(enabled = T, degree = 1),
             width = "500px", height = "500px") %>%
  visIgraphLayout()
```